<!-- Navbar==================================================-->

      <div class="clearfix">
        <div class="row">
          <div class="col-xl-12">
            <form class="form-inline " role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-secondary">Submit</button>
            </form>
            <div>
              <h1 id="navbar">Navbar</h1>
            </div>

            <div class="bs-component">
              <nav class="navbar navbar-light bg-light navbar-expand-md">

                    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      &#x2630;
                    </button>

                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                      <li class="active nav-item"><a href="#" class="nav-link">Link <span class="sr-only">(current)</span></a></li>
                      <li class="nav-item"><a href="#" class="nav-link">Link</a></li>
                      <li class="dropdown nav-item">
                        <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li class="dropdown-item"><a href="#">Action</a></li>
                          <li class="dropdown-item"><a href="#">Another action</a></li>
                          <li class="dropdown-item"><a href="#">Something else here</a></li>
                          <li class="divider dropdown-item"></li>
                          <li class="dropdown-item"><a href="#">Separated link</a></li>
                          <li class="divider dropdown-item"></li>
                          <li class="dropdown-item"><a href="#">One more separated link</a></li>
                        </ul>
                      </li>
                    </ul>

                    <form class="form-inline " role="search">
                      <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                      </div>
                      <button type="submit" class="btn btn-secondary">Submit</button>
                    </form>
                    <ul class="nav navbar-nav ml-auto">
                      <li class="nav-item"><a href="#" class="nav-link">Link</a></li>
                    </ul>
                  </div>
              </nav>
            </div>



            <div class="bs-component">

              <nav class="navbar navbar-dark bg-dark navbar-expand-md">

                    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                      <span class="sr-only">Toggle navigation</span>
                    </button>

                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                    <ul class="nav navbar-nav">
                      <li class="active nav-item"><a href="#" class="nav-link">Link <span class="sr-only">(current)</span></a></li>
                      <li class="nav-item"><a href="#" class="nav-link">Link</a></li>
                      <li class="dropdown nav-item">
                        <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-expanded="true">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li class="dropdown-item"><a href="#">Action</a></li>
                          <li class="dropdown-item"><a href="#">Another action</a></li>
                          <li class="dropdown-item"><a href="#">Something else here</a></li>
                          <li class="divider dropdown-item"></li>
                          <li class="dropdown-item"><a href="#">Separated link</a></li>
                          <li class="divider dropdown-item"></li>
                          <li class="dropdown-item"><a href="#">One more separated link</a></li>
                        </ul>
                      </li>
                    </ul>
                    <ul class="nav navbar-nav ml-auto">
                      <li class="nav-item"><a href="#" class="nav-link">Link</a></li>
                    </ul>
                  </div>



              </nav>

            </div><!-- /example --></div>
</div>
</div>
<!-- Buttons==================================================-->

      <div class="bs-docs-section">
        <div class="">
          <div class="row">
            <div class="col-xl-12">
              <h1 id="buttons">Buttons</h1>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xl-7">
            <p class="bs-component">
              <a href="#" class="btn btn-secondary">Default</a>
              <a href="#" class="btn btn-primary">Primary</a>
              <a href="#" class="btn btn-success">Success</a>
              <a href="#" class="btn btn-info">Info</a>
              <a href="#" class="btn btn-warning">Warning</a>
              <a href="#" class="btn btn-danger">Danger</a>
              <a href="#" class="btn btn-link">Link</a>
            </p>

            <p class="bs-component">
              <a href="#" class="btn btn-secondary disabled">Default</a>
              <a href="#" class="btn btn-primary disabled">Primary</a>
              <a href="#" class="btn btn-success disabled">Success</a>
              <a href="#" class="btn btn-info disabled">Info</a>
              <a href="#" class="btn btn-warning disabled">Warning</a>
              <a href="#" class="btn btn-danger disabled">Danger</a>
              <a href="#" class="btn btn-link disabled">Link</a>
            </p>





            <div style="margin-bottom: 15px;">
              <div class="btn-toolbar bs-component" style="margin: 0;">
                <div class="btn-group">
                  <a href="#" class="btn btn-secondary">Default</a>
                  <a href="#" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-item"><a href="#">Action</a></li>
                    <li class="dropdown-item"><a href="#">Another action</a></li>
                    <li class="dropdown-item"><a href="#">Something else here</a></li>
                    <li class="divider dropdown-item"></li>
                    <li class="dropdown-item"><a href="#">Separated link</a></li>
                  </ul>
                </div>

                <div class="btn-group">
                  <a href="#" class="btn btn-primary">Primary</a>
                  <a href="#" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-item"><a href="#">Action</a></li>
                    <li class="dropdown-item"><a href="#">Another action</a></li>
                    <li class="dropdown-item"><a href="#">Something else here</a></li>
                    <li class="divider dropdown-item"></li>
                    <li class="dropdown-item"><a href="#">Separated link</a></li>
                  </ul>
                </div>



                <div class="btn-group">
                  <a href="#" class="btn btn-success">Success</a>
                  <a href="#" class="btn btn-success dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-item"><a href="#">Action</a></li>
                    <li class="dropdown-item"><a href="#">Another action</a></li>
                    <li class="dropdown-item"><a href="#">Something else here</a></li>
                    <li class="divider dropdown-item"></li>
                    <li class="dropdown-item"><a href="#">Separated link</a></li>
                  </ul>
                </div>



                <div class="btn-group">
                  <a href="#" class="btn btn-info">Info</a>
                  <a href="#" class="btn btn-info dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-item"><a href="#">Action</a></li>
                    <li class="dropdown-item"><a href="#">Another action</a></li>
                    <li class="dropdown-item"><a href="#">Something else here</a></li>
                    <li class="divider dropdown-item"></li>
                    <li class="dropdown-item"><a href="#">Separated link</a></li>
                  </ul>
                </div>

                <div class="btn-group">
                  <a href="#" class="btn btn-warning">Warning</a>
                  <a href="#" class="btn btn-warning dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-item"><a href="#">Action</a></li>
                    <li class="dropdown-item"><a href="#">Another action</a></li>
                    <li class="dropdown-item"><a href="#">Something else here</a></li>
                    <li class="divider dropdown-item"></li>
                    <li class="dropdown-item"><a href="#">Separated link</a></li>
                  </ul>
                </div>
              </div>
            </div>

            <p class="bs-component">
              <a href="#" class="btn btn-lg btn-primary">Large button</a>
              <a href="#" class="btn btn-primary">Default button</a>
              <a href="#" class="btn btn-sm btn-primary">Small button</a>
            </p>
          </div>

          <div class="col-xl-5">
            <p class="bs-component">
              <a href="#" class="btn btn-secondary btn-lg btn-block">Block level button</a>
            </p>
            <div class="bs-component" style="margin-bottom: 15px;">
              <div class="btn-group btn-group-justified">
                <a href="#" class="btn btn-secondary">Left</a>
                <a href="#" class="btn btn-secondary">Middle</a>
                <a href="#" class="btn btn-secondary">Right</a>
              </div>
            </div>

            <div class="bs-component" style="margin-bottom: 15px;">
              <div class="btn-toolbar">
                <div class="btn-group">
                  <a href="#" class="btn btn-secondary">1</a>
                  <a href="#" class="btn btn-secondary">2</a>
                  <a href="#" class="btn btn-secondary">3</a>
                  <a href="#" class="btn btn-secondary">4</a>
                </div>

                <div class="btn-group">
                  <a href="#" class="btn btn-secondary">5</a>
                  <a href="#" class="btn btn-secondary">6</a>
                  <a href="#" class="btn btn-secondary">7</a>
                </div>

                <div class="btn-group">
                  <a href="#" class="btn btn-secondary">8</a>
                  <div class="btn-group">
                    <a href="#" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                      Dropdown
                      <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">
                      <li class="dropdown-item"><a href="#">Dropdown link</a></li>
                      <li class="dropdown-item"><a href="#">Dropdown link</a></li>
                      <li class="dropdown-item"><a href="#">Dropdown link</a></li>
                     </ul>
                  </div>
                </div>
              </div>
            </div>

            <div class="bs-component">
              <div class="btn-group-vertical">
                  <a href="#" class="btn btn-secondary">Stacked Button</a>
                  <a href="#" class="btn btn-secondary">Stacked Button</a>
                  <a href="#" class="btn btn-secondary">Stacked Button</a>
                  <a href="#" class="btn btn-secondary">Stacked Button</a>
              </div>
            </div>

          </div>
        </div>
      </div>

      <!-- Typography

      ================================================== -->
<div class="bs-docs-section">
    <div class="row">
        <div class="col-xl-12">
            <div class="">
                 <h1 id="typography">Typography</h1>
            </div>
        </div>
    </div>
    <!-- Headings -->
    <div class="row">
        <div class="col-xl-4">
            <div class="bs-component">
                 <h1>Heading 1</h1>
                 <h2>Heading 2</h2>
                 <h3>Heading 3</h3>
                 <h4>Heading 4</h4>
                 <h5>Heading 5</h5>
                 <h6>Heading 6</h6>
                <p class="lead">Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
            </div>
        </div>
        <div class="col-xl-4">
            <div class="bs-component">
                 <h2>Example body text</h2>
                <p>Nullam quis risus eget <a href="#">urna mollis ornare</a> vel eu leo. Cum
                    sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus
                    mus. Nullam id dolor id nibh ultricies vehicula.</p>
                <p><small>This line of text is meant to be treated as fine print.</small>
                </p>
                <p>The following snippet of text is <strong>rendered as bold text</strong>.</p>
                <p>The following snippet of text is <em>rendered as italicized text</em>.</p>
                <p>An abbreviation of the word attribute is <abbr title="attribute">attr</abbr>.</p>
            </div>
        </div>
        <div class="col-xl-4">
            <div class="bs-component">
                 <h2>Emphasis classes</h2>
                <p class="text-muted">Fusce dapibus, tellus ac cursus commodo, tortor mauris nibh.</p>
                <p class="text-primary">Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p class="text-warning">Etiam porta sem malesuada magna mollis euismod.</p>
                <p class="text-danger">Donec ullamcorper nulla non metus auctor fringilla.</p>
                <p class="text-success">Duis mollis, est non commodo luctus, nisi erat porttitor ligula.</p>
                <p
                class="text-info">Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
            </div>
        </div>
    </div>
    <!-- Blockquotes -->
    <div class="row">
        <div class="col-xl-12">
             <h2 id="type-blockquotes">Blockquotes</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="bs-component">
              <blockquote class="blockquote">
                <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
              </blockquote>
            </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-12">
          <div class="bs-component">
            <blockquote class="blockquote text-center">
              <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
              <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
            </blockquote>
          </div>
        </div>
        </div>
        <div class="row">
        <div class="col-xl-12">
            <div class="bs-component">
              <blockquote class="blockquote text-right">
                <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
              </blockquote>
            </div>
        </div>

    </div>
</div>
<!-- Tables==================================================-->

      <div class="bs-docs-section">



        <div class="row">

          <div class="col-xl-12">

            <div class="">

              <h1 id="tables">Tables</h1>

            </div>



            <div class="bs-component">

              <table class="table table-striped table-hover ">

                <thead>

                  <tr>

                    <th>#</th>

                    <th>Column heading</th>

                    <th>Column heading</th>

                    <th>Column heading</th>

                  </tr>

                </thead>

                <tbody>

                  <tr>

                    <td>1</td>

                    <td>Column content</td>

                    <td>Column content</td>

                    <td>Column content</td>

                  </tr>

                  <tr>

                    <td>2</td>

                    <td>Column content</td>

                    <td>Column content</td>

                    <td>Column content</td>

                  </tr>

                  <tr class="info">

                    <td>3</td>

                    <td>Column content</td>

                    <td>Column content</td>

                    <td>Column content</td>

                  </tr>

                  <tr class="success">

                    <td>4</td>

                    <td>Column content</td>

                    <td>Column content</td>

                    <td>Column content</td>

                  </tr>

                  <tr class="danger">

                    <td>5</td>

                    <td>Column content</td>

                    <td>Column content</td>

                    <td>Column content</td>

                  </tr>

                  <tr class="warning">

                    <td>6</td>

                    <td>Column content</td>

                    <td>Column content</td>

                    <td>Column content</td>

                  </tr>

                  <tr class="active">

                    <td>7</td>

                    <td>Column content</td>

                    <td>Column content</td>

                    <td>Column content</td>

                  </tr>

                </tbody>

              </table>

            </div><!-- /example --></div>
</div>
</div>
<!-- Forms==================================================-->

      <div class="bs-docs-section">

        <div class="row">

          <div class="col-xl-12">

            <div class="">

              <h1 id="forms">Forms</h1>

            </div>

          </div>

        </div>



        <div class="row">

          <div class="col-xl-6">

            <div class="card bg-light card-body mb-3 bs-component">

              <form class="">

                <fieldset>

                  <legend>Legend</legend>

                  <div class="form-group">

                    <label for="inputEmail" class="col-xl-2 col-form-label">Email</label>

                    <div class="col-xl-10">

                      <input type="text" class="form-control" id="inputEmail" placeholder="Email">

                    </div>

                  </div>

                  <div class="form-group">

                    <label for="inputPassword" class="col-xl-2 col-form-label">Password</label>

                    <div class="col-xl-10">

                      <input type="password" class="form-control" id="inputPassword" placeholder="Password">

                      <div class="form-check">

                        <label>

                          <input type="checkbox"> Checkbox

                        </label>

                      </div>

                    </div>

                  </div>

                  <div class="form-group">

                    <label for="textArea" class="col-xl-2 col-form-label">Textarea</label>

                    <div class="col-xl-10">

                      <textarea class="form-control" rows="3" id="textArea"></textarea>

                      <span class="form-text">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>

                    </div>

                  </div>

                  <div class="form-group">

                    <label class="col-xl-2 col-form-label">Radios</label>

                    <div class="col-xl-10">

                      <div class="form-check">

                        <label>

                          <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>

                          Option one is this

                        </label>

                      </div>

                      <div class="form-check">

                        <label>

                          <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">

                          Option two can be something else

                        </label>

                      </div>

                    </div>

                  </div>

                  <div class="form-group">

                    <label for="select" class="col-xl-2 col-form-label">Selects</label>

                    <div class="col-xl-10">

                      <select class="form-control" id="select">

                        <option>1</option>

                        <option>2</option>

                        <option>3</option>

                        <option>4</option>

                        <option>5</option>

                      </select>

                      <br>

                      <select multiple class="form-control">

                        <option>1</option>

                        <option>2</option>

                        <option>3</option>

                        <option>4</option>

                        <option>5</option>

                      </select>

                    </div>

                  </div>

                  <div class="form-group">

                    <div class="col-xl-10 offset-lg-2">

                      <button type="reset" class="btn btn-secondary">Cancel</button>

                      <button type="submit" class="btn btn-primary">Submit</button>

                    </div>

                  </div>

                </fieldset>

              </form>

            </div>

          </div>

          <div class="col-xl-4 offset-lg-1">



              <form class="bs-component">

                <div class="form-group">

                  <label class="col-form-label" for="focusedInput">Focused input</label>

                  <input class="form-control" id="focusedInput" type="text" value="This is focused...">

                </div>



                <div class="form-group">

                  <label class="col-form-label" for="disabledInput">Disabled input</label>

                  <input class="form-control" id="disabledInput" type="text" placeholder="Disabled input here..." disabled>

                </div>



                <div class="form-group has-warning">

                  <label class="col-form-label" for="inputWarning">Input warning</label>

                  <input type="text" class="form-control" id="inputWarning">

                </div>



                <div class="form-group has-error">

                  <label class="col-form-label" for="inputError">Input error</label>

                  <input type="text" class="form-control" id="inputError">

                </div>



                <div class="form-group has-success">

                  <label class="col-form-label" for="inputSuccess">Input success</label>

                  <input type="text" class="form-control" id="inputSuccess">

                </div>



                <div class="form-group">

                  <label class="col-form-label" for="inputLarge">Large input</label>

                  <input class="form-control form-control-lg" type="text" id="inputLarge">

                </div>



                <div class="form-group">

                  <label class="col-form-label" for="inputDefault">Default input</label>

                  <input type="text" class="form-control" id="inputDefault">

                </div>



                <div class="form-group">

                  <label class="col-form-label" for="inputSmall">Small input</label>

                  <input class="form-control form-control-sm" type="text" id="inputSmall">

                </div>



                <div class="form-group">

                  <label class="col-form-label">Input addons</label>

                  <div class="input-group">

                    <span class="input-group-addon">$</span>

                    <input type="text" class="form-control">

                    <span class="input-group-btn">

                      <button class="btn btn-secondary" type="button">Button</button>

                    </span>

                  </div>

                </div>

              </form>



          </div>

        </div>

      </div>



      <!-- Navs

      ================================================== -->
<div class="bs-docs-section">
    <div class="row">
        <div class="col-xl-12">
            <div class="">
                 <h1 id="navs">Navs</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-4">
             <h2 id="nav-tabs">Tabs</h2>
            <div class="bs-component">
                <ul class="nav nav-tabs">
                    <li class="active nav-item"><a href="#home" data-toggle="tab" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item"><a href="#profile" data-toggle="tab" class="nav-link">Profile</a>
                    </li>
                    <li class="disabled nav-item"><a class="nav-link">Disabled</a>
                    </li>
                    <li class="dropdown nav-item"> <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="#">

                    Dropdown <span class="caret"></span>

                  </a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-item"><a href="#dropdown1" data-toggle="tab">Action</a>
                            </li>
                            <li class="divider dropdown-item"></li>
                            <li class="dropdown-item"><a href="#dropdown2" data-toggle="tab">Another action</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade active in">
                        <p>Raw denim you probably haven&apos;t heard of them jean shorts Austin.
                            Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche
                            tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro
                            keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry
                            richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip
                            quis cardigan american apparel, butcher voluptate nisi qui.</p>
                    </div>
                    <div class="tab-pane fade" id="profile">
                        <p>Food truck fixie locavore, accusamus mcsweeney&apos;s marfa nulla single-origin
                            coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings
                            next level wes anderson artisan four loko farm-to-table craft beer twee.
                            Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean
                            shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore
                            aesthetic magna delectus mollit.</p>
                    </div>
                    <div class="tab-pane fade" id="dropdown1">
                        <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out
                            mcsweeney&apos;s organic lomo retro fanny pack lo-fi farm-to-table readymade.
                            Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard
                            locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy
                            irony. Leggings gentrify squid 8-bit cred pitchfork.</p>
                    </div>
                    <div class="tab-pane fade" id="dropdown2">
                        <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party
                            before they sold out master cleanse gluten-free squid scenester freegan
                            cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf
                            cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR,
                            banh mi before they sold out farm-to-table VHS viral locavore cosby sweater.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-4">
             <h2 id="nav-pills">Pills</h2>
            <div class="bs-component">
                <ul class="nav nav-pills">
                    <li class="active nav-item"><a href="#" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item"><a href="#" class="nav-link">Profile</a>
                    </li>
                    <li class="disabled nav-item"><a href="#" class="nav-link">Disabled</a>
                    </li>
                    <li class="dropdown nav-item"> <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="#">

                    Dropdown <span class="caret"></span>

                  </a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-item"><a href="#">Action</a>
                            </li>
                            <li class="dropdown-item"><a href="#">Another action</a>
                            </li>
                            <li class="dropdown-item"><a href="#">Something else here</a>
                            </li>
                            <li class="divider dropdown-item"></li>
                            <li class="dropdown-item"><a href="#">Separated link</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <br>
            <div class="bs-component">
                <ul class="nav nav-pills flex-column">
                    <li class="active nav-item"><a href="#" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item"><a href="#" class="nav-link">Profile</a>
                    </li>
                    <li class="disabled nav-item"><a href="#" class="nav-link">Disabled</a>
                    </li>
                    <li class="dropdown nav-item"> <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="#">

                    Dropdown <span class="caret"></span>

                  </a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-item"><a href="#">Action</a>
                            </li>
                            <li class="dropdown-item"><a href="#">Another action</a>
                            </li>
                            <li class="dropdown-item"><a href="#">Something else here</a>
                            </li>
                            <li class="divider dropdown-item"></li>
                            <li class="dropdown-item"><a href="#">Separated link</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-xl-4">
             <h2 id="nav-breadcrumbs">Breadcrumbs</h2>
            <div class="bs-component">
                <ul class="breadcrumb">
                    <li class="active">Home</li>
                </ul>
                <ul class="breadcrumb">
                    <li><a href="#">Home</a>
                    </li>
                    <li class="active">Library</li>
                </ul>
                <ul class="breadcrumb">
                    <li><a href="#">Home</a>
                    </li>
                    <li><a href="#">Library</a>
                    </li>
                    <li class="active">Data</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-4">
             <h2 id="pagination">Pagination</h2>
            <div class="bs-component">
                <ul class="pagination">
                    <li class="disabled page-item"><a href="#" class="page-link">&#xAB;</a>
                    </li>
                    <li class="active page-item"><a href="#" class="page-link">1</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">2</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">3</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">4</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">5</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">&#xBB;</a>
                    </li>
                </ul>
                <ul class="pagination pagination-lg">
                    <li class="disabled page-item"><a href="#" class="page-link">&#xAB;</a>
                    </li>
                    <li class="active page-item"><a href="#" class="page-link">1</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">2</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">3</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">&#xBB;</a>
                    </li>
                </ul>
                <ul class="pagination pagination-sm">
                    <li class="disabled page-item"><a href="#" class="page-link">&#xAB;</a>
                    </li>
                    <li class="active page-item"><a href="#" class="page-link">1</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">2</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">3</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">4</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">5</a>
                    </li>
                    <li class="page-item"><a href="#" class="page-link">&#xBB;</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-xl-4">
             <h2 id="pager">Pager</h2>
            <div class="bs-component">
                <ul class="pager">
                    <li><a href="#">Previous</a>
                    </li>
                    <li><a href="#">Next</a>
                    </li>
                </ul>
                <ul class="pager">
                    <li class="previous disabled"><a href="#">&#x2190; Older</a>
                    </li>
                    <li class="next"><a href="#">Newer &#x2192;</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-xl-4"></div>
    </div>
</div>
<!-- Indicators==================================================-->

      <div class="bs-docs-section">



        <div class="row">

          <div class="col-xl-12">

            <div class="">

              <h1 id="indicators">Indicators</h1>

            </div>

          </div>

        </div>



        <div class="row">

          <div class="col-xl-12">

            <h2>Alerts</h2>

            <div class="bs-component">

              <div class="alert alert-dismissible alert-warning">

                <button type="button" class="close" data-dismiss="alert">&#xD7;</button>

                <h4>Warning!</h4>

                <p>Best check yo self, you&apos;re not looking too good. Nulla vitae elit libero, a pharetra augue. Praesent commodo cursus magna, <a href="#" class="alert-link">vel scelerisque nisl consectetur et</a>.</p>

              </div>

            </div>

          </div>

        </div>

        <div class="row">

          <div class="col-xl-4">

            <div class="bs-component">

              <div class="alert alert-dismissible alert-danger">

                <button type="button" class="close" data-dismiss="alert">&#xD7;</button>

                <strong>Oh snap!</strong> <a href="#" class="alert-link">Change a few things up</a> and try submitting again.

              </div>

            </div>

          </div>

          <div class="col-xl-4">

            <div class="bs-component">

              <div class="alert alert-dismissible alert-success">

                <button type="button" class="close" data-dismiss="alert">&#xD7;</button>

                <strong>Well done!</strong> You successfully read <a href="#" class="alert-link">this important alert message</a>.

              </div>

            </div>

          </div>

          <div class="col-xl-4">

            <div class="bs-component">

              <div class="alert alert-dismissible alert-info">

                <button type="button" class="close" data-dismiss="alert">&#xD7;</button>

                <strong>Heads up!</strong> This <a href="#" class="alert-link">alert needs your attention</a>, but it&apos;s not super important.

              </div>

            </div>

          </div>

        </div>

        <div class="row">

          <div class="col-xl-4">

            <h2>Labels</h2>

            <div class="bs-component" style="margin-bottom: 40px;">

              <span class="badge badge-dark">Default</span>

              <span class="badge badge-primary">Primary</span>

              <span class="badge badge-success">Success</span>

              <span class="badge badge-warning">Warning</span>

              <span class="badge badge-danger">Danger</span>

              <span class="badge badge-info">Info</span>

            </div>

          </div>

          <div class="col-xl-4">

            <h2>Badges</h2>

            <div class="bs-component">

              <ul class="nav nav-pills">

                <li class="active nav-item"><a href="#" class="nav-link">Home <span class="badge">42</span></a></li>

                <li class="nav-item"><a href="#" class="nav-link">Profile <span class="badge"></span></a></li>

                <li class="nav-item"><a href="#" class="nav-link">Messages <span class="badge">3</span></a></li>

              </ul>

            </div>

          </div>

        </div>

      </div>



      <!-- Progress bars

      ================================================== -->
<div class="bs-docs-section">
    <div class="row">
        <div class="col-xl-12">
            <div class="">
                 <h1 id="progress-bars">Progress bars</h1>
            </div>
             <h3 id="progress-basic">Basic</h3>
            <div class="bs-component">
                <div class="progress">
                    <div class="progress-bar" style="width: 60%;"></div>
                </div>
            </div>
             <h3 id="progress-alternatives">Contextual alternatives</h3>
            <div class="bs-component">
                <div class="progress">
                    <div class="progress-bar progress-bar-info" style="width: 20%"></div>
                </div>
                <div class="progress">
                    <div class="progress-bar progress-bar-success" style="width: 40%"></div>
                </div>
                <div class="progress">
                    <div class="progress-bar progress-bar-warning" style="width: 60%"></div>
                </div>
                <div class="progress">
                    <div class="progress-bar progress-bar-danger" style="width: 80%"></div>
                </div>
            </div>
             <h3 id="progress-striped">Striped</h3>
            <div class="bs-component">
                <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-info" style="width: 20%"></div>
                </div>
                <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-success" style="width: 40%"></div>
                </div>
                <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-warning" style="width: 60%"></div>
                </div>
                <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-danger" style="width: 80%"></div>
                </div>
            </div>
             <h3 id="progress-animated">Animated</h3>
            <div class="bs-component">
                <div class="progress progress-striped active">
                    <div class="progress-bar" style="width: 45%"></div>
                </div>
            </div>
             <h3 id="progress-stacked">Stacked</h3>
            <div class="bs-component">
                <div class="progress">
                    <div class="progress-bar progress-bar-success" style="width: 35%"></div>
                    <div class="progress-bar progress-bar-warning" style="width: 20%"></div>
                    <div class="progress-bar progress-bar-danger" style="width: 10%"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Containers==================================================-->

      <div class="bs-docs-section">



        <div class="row">

          <div class="col-xl-12">

            <div class="">

              <h1 id="containers">Containers</h1>

            </div>

            <div class="bs-component">

              <div class="jumbotron">

                <h1>Jumbotron</h1>

                <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>

                <p><a class="btn btn-primary btn-lg">Learn more</a></p>

              </div>

            </div>

          </div>

        </div>





        <div class="row">

          <div class="col-xl-12">

            <h2>List groups</h2>

          </div>

        </div>

        <div class="row">

          <div class="col-xl-4">

            <div class="bs-component">

              <ul class="list-group">

                <li class="list-group-item">

                  <span class="badge">14</span>

                  Cras justo odio

                </li>

                <li class="list-group-item">

                  <span class="badge">2</span>

                  Dapibus ac facilisis in

                </li>

                <li class="list-group-item">

                  <span class="badge">1</span>

                  Morbi leo risus

                </li>

              </ul>

            </div>

          </div>

          <div class="col-xl-4">

            <div class="bs-component">

              <div class="list-group">

                <a href="#" class="list-group-item active">

                  Cras justo odio

                </a>

                <a href="#" class="list-group-item">Dapibus ac facilisis in

                </a>

                <a href="#" class="list-group-item">Morbi leo risus

                </a>

              </div>

            </div>

          </div>

          <div class="col-xl-4">

            <div class="bs-component">

              <div class="list-group">

                <a href="#" class="list-group-item">

                  <h4 class="list-group-item-heading">List group item heading</h4>

                  <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>

                </a>

                <a href="#" class="list-group-item">

                  <h4 class="list-group-item-heading">List group item heading</h4>

                  <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>

                </a>

              </div>

            </div>

          </div>

        </div>





        <div class="row">

          <div class="col-xl-12">

            <h2>Cards</h2>

          </div>

        </div>

        <div class="row">

          <div class="col-xl-4">

            <div class="bs-component">

              <div class="card">

                <div class="card-body">

                  Basic card

                </div>

              </div>



              <div class="card">

                <div class="card-header"> heading</div>

                <div class="card-body">

                   content

                </div>

              </div>



              <div class="card">

                <div class="card-body">

                   content

                </div>

                <div class="card-footer"> footer</div>

              </div>

            </div>

          </div>

          <div class="col-xl-4">

            <div class="bs-component">

              <div class="card text-white bg-primary">

                <div class="card-header">

                  <h3 class="card-title"> primary</h3>

                </div>

                <div class="card-body">

                   content

                </div>

              </div>



              <div class="card text-white bg-success">

                <div class="card-header">

                  <h3 class="card-title"> success</h3>

                </div>

                <div class="card-body">

                   content

                </div>

              </div>



              <div class="card text-white bg-warning">

                <div class="card-header">
                  <h3 class="card-title"> warning</h3>
                </div>
                <div class="card-body">
                   content
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-4">
            <div class="bs-component">
              <div class="card text-white bg-danger">
                <div class="card-header">
                  <h3 class="card-title"> danger</h3>
                </div>
                <div class="card-body">
                   content
                </div>
              </div>

              <div class="card text-white bg-info">
                <div class="card-header">
                  <h3 class="card-title"> info</h3>
                </div>
                <div class="card-body">
                   content
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>



      <!-- Dialogs

      ================================================== -->
<div class="bs-docs-section">
    <div class="row">
        <div class="col-xl-12">
            <div class="">
                 <h1 id="dialogs">Dialogs</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6">
             <h2>Modals</h2>
            <div class="bs-component">
                <div class="modal">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&#xD7;</button>
                                 <h4 class="modal-title">Modal title</h4>
                            </div>
                            <div class="modal-body">
                                <p>One fine body&#x2026;</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary">Save changes</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-6">
             <h2>Popovers</h2>
            <div class="bs-component">
                <button type="button" class="btn btn-secondary" data-container="body"
                data-toggle="popover" data-placement="left" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">Left</button>
                <button type="button" class="btn btn-secondary" data-container="body"
                data-toggle="popover" data-placement="top" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">Top</button>
                <button type="button" class="btn btn-secondary" data-container="body"
                data-toggle="popover" data-placement="bottom" data-content="Vivamus

              sagittis lacus vel augue laoreet rutrum faucibus.">Bottom</button>
                <button type="button" class="btn btn-secondary" data-container="body"
                data-toggle="popover" data-placement="right" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">Right</button>
            </div>
             <h2>Tooltips</h2>
            <div class="bs-component">
                <button type="button" class="btn btn-secondary" data-toggle="tooltip"
                data-placement="left" title="" data-original-title="Tooltip on left">Left</button>
                <button type="button" class="btn btn-secondary" data-toggle="tooltip"
                data-placement="top" title="" data-original-title="Tooltip on top">Top</button>
                <button type="button" class="btn btn-secondary" data-toggle="tooltip"
                data-placement="bottom" title="" data-original-title="Tooltip on bottom">Bottom</button>
                <button type="button" class="btn btn-secondary" data-toggle="tooltip"
                data-placement="right" title="" data-original-title="Tooltip on right">Right</button>
            </div>
        </div>
    </div>
</div>
<div id="source-modal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&#xD7;</button>
                 <h4 class="modal-title">Source Code</h4>
            </div>
            <div class="modal-body"> <pre></pre>
            </div>
        </div>
    </div>
</div>
