<ul class="nav nav-pills nav-fill">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $path =  $_SERVER["REQUEST_URI"]; ?>
            <li class="nav-item" role="presentation">
                <a class="nav-link<?php if($page->getHref() === $path) echo ' active'?>" href="<?php echo $page->getHref() ?>">
                    <?php echo $this->translate($page->getLabel()) ?>
                </a>
            </li>
        <?php $count++ ?>
    <?php endforeach; ?>
</ul>
