<!-- <div class="list-group table-of-contents bg-light">
    <?php $count = 0 ?>
    <?php foreach ($this->container as $page): ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
			<?php $hasChildren = $page->hasPages() ?>
			<?php if( ! $hasChildren): ?>
			<a class="list-group-item<?php if($page->isActive()) echo ' active'?>" href="<?php echo $page->getHref() ?>">
				<?php echo $this->translate($page->getLabel()) ?>
			</a>
        <?php else: ?>
//added php if statements here-- didnt seem to make a change
                <div class="collapse" id="spage_<?php echo $count ?>">
                    <?php foreach($page->getPages() as $child): ?>
                        <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)): continue; ?>
                      <?php endif; ?>
                            <?php if (get_theme_option('sidebar_position') == 'Right'): ?>
                              <a style="padding-left:30px; font-size:90%" class="list-group-item <?php if($page->isActive()) echo 'active'; ?>" href="<?php echo $child->getHref() ?>">
                                  <?php echo $this->translate($child->getLabel()) ?>
                                </a>
                                <?php endif; ?>
                            <?php if (get_theme_option('sidebar_position') == 'Left'): ?>
                              <a style="padding-left:130px; font-size:90%" class="list-group-item <?php if($page->isActive()) echo 'active'; ?>" href="<?php echo $child->getHref() ?>">
                                  <?php echo $this->translate($child->getLabel()) ?>
                                </a>
                            <?php else: ?>
                              <a style="padding-left:0px; font-size:0%" class="list-group-item <?php if($page->isActive()) echo 'active'; ?>" href="<?php echo $child->getHref() ?>">
                                </a>
                                <?php endif; ?>
                    <?php endforeach; ?>
                </div>
              
        <?php endif; ?>		
        <?php $count++ ?>
    <?php endforeach; ?>
</div> -->
<nav class="navbar navbar-light bg-light">
    <?php $count = 0 ?>
    <ul class="navbar-nav mr-auto">
    <?php foreach ($this->container as $page): ?>
        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
      <?php $hasChildren = $page->hasPages() ?>
      
      <?php if( ! $hasChildren): ?>
      <a class="nav-link<?php if($page->isActive()) echo ' active'?>" href="<?php echo $page->getHref() ?>">
        <?php echo $this->translate($page->getLabel()) ?>
      </a>
        <?php else: ?>
<!-- added php if statements here-- didnt seem to make a change -->
                <div class="collapse" id="spage_<?php echo $count ?>">
                    <?php foreach($page->getPages() as $child): ?>
                        <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)): continue; ?>
                      <?php endif; ?>
                            <?php if (get_theme_option('sidebar_position') == 'Right'): ?>
                              <a style="padding-left:30px; font-size:90%" class="list-group-item <?php if($page->isActive()) echo 'active'; ?>" href="<?php echo $child->getHref() ?>">
                                  <?php echo $this->translate($child->getLabel()) ?>
                                </a>
                                <?php endif; ?>
                            <?php if (get_theme_option('sidebar_position') == 'Left'): ?>
                              <a style="padding-left:130px; font-size:90%" class="list-group-item <?php if($page->isActive()) echo 'active'; ?>" href="<?php echo $child->getHref() ?>">
                                  <?php echo $this->translate($child->getLabel()) ?>
                                </a>
                            <?php else: ?>
                              <a style="padding-left:0px; font-size:0%" class="list-group-item <?php if($page->isActive()) echo 'active'; ?>" href="<?php echo $child->getHref() ?>">
                                </a>
                                <?php endif; ?>
                    <?php endforeach; ?>
                </div>
              
        <?php endif; ?>  

        <?php $count++ ?>
    <?php endforeach; ?>
    </ul> 
</nav>