  <!-- Masthead -->
  <?php
      if (isset($title)) { $titleParts[] = strip_formatting($title); }
      $titleParts[] = option('site_title');
  ?>
    <!-- Adds "container" for Framed or "container-fluid for full width" -->
   <header id="banner" class="right">
    <div class="row m-0">
    <!-- Card with image overlay for header image, heading and text -->
      <div class="my-auto mx-auto text-center col-lg-7 p-5">
          <?php if ((get_theme_option('header_image_heading') !== '')): ?>
            <h1 class="display-3" style="<?php $color =  get_theme_option('header_image_heading_color');
            if($color !="default"):
              echo "color:", $color;
            endif; ?>"><?php echo get_theme_option('header_image_heading'); ?></h1>
          <?php endif; ?>
          <?php if ((get_theme_option('header_image_text') !== '')): ?>
            <p class="card-text"><?php echo get_theme_option('header_image_text'); ?></p>
          <?php endif; ?>
    <!-- Buttons to add "call to action". Maybe replace with just one and form field? -->
          <div class="bs-component">
            <a href="<?php echo html_escape(url('items')); ?>" class="btn btn-secondary btn-outline-dark"> Browse Items</a>
            <a href="<?php echo html_escape(url('collections')); ?>" class="btn btn-secondary btn-outline-dark">Browse Collections</a>
          </div>
        </div>
        <div class="p-5 col-lg-5">
          <img src="<?php
          if ((get_theme_option('Header Background Image') === null)){
            echo img('defaulthbg.jpg');
          }
          else echo bs_header_bg();
          ?>" class="card-img" alt="background image">
          <!--<div class="card-img-overlay d-flex">
          </div>-->
        </div>
      </div>
  </header>
