  <!-- Masthead -->
  <?php
      if (isset($title)) { $titleParts[] = strip_formatting($title); }
      $titleParts[] = option('site_title');
  ?>
    <!-- Adds "container" for Framed or "container-fluid for full width" -->
   <header id="banner" class="<?php echo get_theme_option('header_flow'); ?> page-header">

    <!-- Card with image overlay for header image, heading and text -->
    <div class="card bg-dark text-white text-center">
      <img src="<?php
      if ((get_theme_option('Header Background Image') === null)){
        echo img('defaulthbg.jpg');
      }
      else echo bs_header_bg();
      ?>" class="card-img" alt="background image">
      <div class="card-img-overlay d-flex">
        <div class="my-auto mx-auto text-center">
  				<?php if ((get_theme_option('header_image_heading') !== '')): ?>
  					<h1 class="card-title"><?php echo get_theme_option('header_image_heading'); ?></h1>
  				<?php endif; ?>
  				<?php if ((get_theme_option('header_image_text') !== '')): ?>
  					<p class="card-text"><?php echo get_theme_option('header_image_text'); ?></p>
  				<?php endif; ?>
    <!-- Buttons to add "call to action". Maybe replace with just one and form field? -->
          <div class="bs-component">
            <a href="<?php echo html_escape(url('items')); ?>" class="btn btn-secondary"> Browse Items</a>
            <a href="<?php echo html_escape(url('collections')); ?>" class="btn btn-secondary">Browse Collections</a>
          </div>
        </div>
      </div>
    </div>
  </header>
  <main id="content">
     <div class="container">